#include "web_interface.h"

// 网页界面HTML内容
static const char* web_page_html = 
"<!DOCTYPE html>"
"<html><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>电机多模式控制</title>"
"<style>"
"body{font-family:Arial,sans-serif;max-width:700px;margin:30px auto;padding:20px;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%)}"
".container{background:white;padding:30px;border-radius:15px;box-shadow:0 8px 32px rgba(0,0,0,0.3)}"
"h1{color:#333;text-align:center;margin-bottom:30px;font-size:28px}"
".mode-section{margin-bottom:25px;padding:20px;border:2px solid #e0e0e0;border-radius:10px;background:#f9f9f9}"
".mode-title{font-size:18px;font-weight:bold;color:#333;margin-bottom:15px;display:flex;align-items:center}"
".mode-title:before{content:'●';color:#4CAF50;margin-right:8px;font-size:20px}"
".form-group{margin-bottom:15px;display:flex;align-items:center;gap:10px}"
"label{min-width:100px;font-weight:bold;color:#555}"
"input[type='number'],select{padding:8px 12px;border:2px solid #ddd;border-radius:5px;font-size:14px;flex:1}"
"input[type='number']:focus,select:focus{border-color:#4CAF50;outline:none}"
"input[type='radio']{margin-right:8px}"
".radio-group{display:flex;gap:20px;margin-bottom:20px;justify-content:center}"
".radio-option{display:flex;align-items:center;padding:10px 15px;border:2px solid #ddd;border-radius:8px;cursor:pointer;transition:all 0.3s}"
".radio-option:hover{background:#f0f0f0}"
".radio-option.active{border-color:#4CAF50;background:#e8f5e8}"
".btn{background:#4CAF50;color:white;padding:10px 20px;border:none;border-radius:5px;cursor:pointer;font-size:14px;margin:3px;transition:all 0.3s}"
".btn:hover{background:#45a049;transform:translateY(-1px)}"
".btn-danger{background:#f44336}"
".btn-danger:hover{background:#d32f2f}"
".btn-warning{background:#ff9800}"
".btn-warning:hover{background:#f57c00}"
".btn-info{background:#2196F3}"
".btn-info:hover{background:#1976D2}"
".control-panel{display:flex;justify-content:center;gap:10px;margin:20px 0;flex-wrap:wrap}"
".status{margin-top:20px;padding:15px;border-radius:8px;background:#e3f2fd;border-left:4px solid #2196F3}"
".mode-content{display:none}"
".mode-content.active{display:block}"
".unit{color:#888;font-size:12px;margin-left:5px}"
"</style>"
"</head><body>"
"<div class='container'>"
"<h1>⚙️ 电机多模式控制系统</h1>"

"<div class='radio-group'>"
"<div class='radio-option active' onclick='selectMode(\"velocity\")'>"
"<input type='radio' name='mode' value='velocity' checked id='mode-velocity'>"
"<label for='mode-velocity'>🏃 速度模式</label>"
"</div>"
"<div class='radio-option' onclick='selectMode(\"position\")'>"
"<input type='radio' name='mode' value='position' id='mode-position'>"
"<label for='mode-position'>📍 位置模式</label>"
"</div>"
"<div class='radio-option' onclick='selectMode(\"torque\")'>"
"<input type='radio' name='mode' value='torque' id='mode-torque'>"
"<label for='mode-torque'>💪 力矩模式</label>"
"</div>"
"</div>"

"<div id='velocity-content' class='mode-content active'>"
"<div class='mode-section'>"
"<div class='mode-title'>速度控制</div>"
"<div class='form-group'>"
"<label>目标速度:</label>"
"<input type='number' id='velocity' step='0.1' placeholder='请输入速度值'>"
"<span class='unit'>r/s</span>"
"<button class='btn' onclick='setVelocity()'>设置速度</button>"
"</div>"
"</div>"
"</div>"

"<div id='position-content' class='mode-content'>"
"<div class='mode-section'>"
"<div class='mode-title'>位置控制</div>"
"<div class='form-group'>"
"<label>目标位置:</label>"
"<input type='number' id='position' step='0.1' placeholder='请输入位置值'>"
"<span class='unit'>位置值</span>"
"<button class='btn' onclick='setPosition()'>设置位置</button>"
"</div>"
"<div class='form-group'>"
"<label>角度输入:</label>"
"<input type='number' id='angle' step='0.1' placeholder='请输入角度值'>"
"<span class='unit'>度</span>"
"<button class='btn' onclick='setAngle()'>设置角度</button>"
"</div>"
"</div>"
"</div>"

"<div id='torque-content' class='mode-content'>"
"<div class='mode-section'>"
"<div class='mode-title'>力矩控制</div>"
"<div class='form-group'>"
"<label>目标力矩:</label>"
"<input type='number' id='torque' step='0.01' placeholder='请输入力矩值'>"
"<span class='unit'>Nm</span>"
"<button class='btn' onclick='setTorque()'>设置力矩</button>"
"</div>"
"</div>"
"</div>"

"<div class='control-panel'>"
"<button class='btn btn-info' onclick='enableMotor()'>🔋 使能电机</button>"
"<button class='btn btn-danger' onclick='disableMotor()'>🔌 失能电机</button>"
"<button class='btn btn-warning' onclick='clearErrors()'>🔧 清除错误</button>"
"</div>"

"<div class='status'>"
"<strong>当前状态:</strong> <span id='status'>系统就绪，请选择工作模式</span>"
"</div>"
"</div>"

"<script>"
"let currentMode='velocity';"
"function selectMode(mode){"
"currentMode=mode;"
"document.querySelectorAll('.mode-content').forEach(el=>el.classList.remove('active'));"
"document.querySelectorAll('.radio-option').forEach(el=>el.classList.remove('active'));"
"document.getElementById(mode+'-content').classList.add('active');"
"event.currentTarget.classList.add('active');"
"document.getElementById('mode-'+mode).checked=true;"
"fetch('/set_mode?mode='+mode).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='模式切换: '+getModeName(mode)+' | '+d;"
"}).catch(e=>console.log('模式切换失败: '+e));"
"}"
"function getModeName(mode){"
"const names={'velocity':'速度模式','position':'位置模式','torque':'力矩模式'};"
"return names[mode]||mode;"
"}"
"function setVelocity(){"
"let vel=document.getElementById('velocity').value;"
"if(vel===''){alert('请输入速度值');return;}"
"fetch('/set_velocity?value='+vel).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='速度设置: '+vel+' r/s | '+d;"
"}).catch(e=>alert('设置失败: '+e));"
"}"
"function setPosition(){"
"let pos=document.getElementById('position').value;"
"if(pos===''){alert('请输入位置值');return;}"
"fetch('/set_position?value='+pos).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='位置设置: '+pos+' | '+d;"
"}).catch(e=>alert('设置失败: '+e));"
"}"
"function setAngle(){"
"let angle=document.getElementById('angle').value;"
"if(angle===''){alert('请输入角度值');return;}"
"fetch('/set_angle?value='+angle).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='角度设置: '+angle+'° | '+d;"
"}).catch(e=>alert('设置失败: '+e));"
"}"
"function setTorque(){"
"let torque=document.getElementById('torque').value;"
"if(torque===''){alert('请输入力矩值');return;}"
"fetch('/set_torque?value='+torque).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='力矩设置: '+torque+' Nm | '+d;"
"}).catch(e=>alert('设置失败: '+e));"
"}"
"function enableMotor(){"
"fetch('/enable').then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='电机已使能 | '+d;"
"}).catch(e=>alert('操作失败: '+e));"
"}"
"function disableMotor(){"
"fetch('/disable').then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='电机已失能 | '+d;"
"}).catch(e=>alert('操作失败: '+e));"
"}"
"function clearErrors(){"
"fetch('/clear').then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='错误已清除 | '+d;"
"}).catch(e=>alert('操作失败: '+e));"
"}"
"</script>"
"</body></html>";

// 调试页面HTML内容
static const char* debug_page_html = 
"<!DOCTYPE html>"
"<html><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>电机调试工具</title>"
"<style>"
"body{font-family:Arial,sans-serif;max-width:800px;margin:30px auto;padding:20px;background:linear-gradient(135deg,#ff7e5f 0%,#feb47b 100%)}"
".container{background:white;padding:30px;border-radius:15px;box-shadow:0 8px 32px rgba(0,0,0,0.3)}"
"h1{color:#333;text-align:center;margin-bottom:30px;font-size:28px}"
".debug-section{margin-bottom:25px;padding:20px;border:2px solid #e0e0e0;border-radius:10px;background:#f9f9f9}"
".section-title{font-size:18px;font-weight:bold;color:#333;margin-bottom:15px;display:flex;align-items:center}"
".section-title:before{content:'🔧';margin-right:8px;font-size:20px}"
".btn-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:15px;margin:20px 0}"
".btn{background:#4CAF50;color:white;padding:12px 20px;border:none;border-radius:8px;cursor:pointer;font-size:14px;transition:all 0.3s;text-align:center}"
".btn:hover{background:#45a049;transform:translateY(-2px);box-shadow:0 4px 8px rgba(0,0,0,0.2)}"
".btn-restart{background:#ff9800}"
".btn-restart:hover{background:#f57c00}"
".btn-query{background:#2196F3}"
".btn-query:hover{background:#1976D2}"
".exception-group{display:flex;align-items:center;gap:10px;margin-bottom:15px}"
"select{padding:8px 12px;border:2px solid #ddd;border-radius:5px;font-size:14px}"
".status{margin-top:20px;padding:15px;border-radius:8px;background:#e8f5e8;border-left:4px solid #4CAF50;font-family:monospace;max-height:200px;overflow-y:auto}"
".nav-link{display:inline-block;margin:10px 0;color:#2196F3;text-decoration:none;font-weight:bold}"
".nav-link:hover{text-decoration:underline}"
"</style>"
"</head><body>"
"<div class='container'>"
"<h1>🔧 电机调试工具</h1>"
"<a href='/' class='nav-link'>← 返回主控制页面</a>"

"<div class='debug-section'>"
"<div class='section-title'>电机控制指令</div>"
"<div class='btn-grid'>"
"<button class='btn btn-restart' onclick='restartMotor()'>🔄 重启电机</button>"
"</div>"
"</div>"

"<div class='debug-section'>"
"<div class='section-title'>电机状态查询</div>"
"<div class='btn-grid'>"
"<button class='btn btn-query' onclick='queryTorque()'>💪 查询力矩</button>"
"<button class='btn btn-query' onclick='queryPower()'>⚡ 查询功率</button>"
"<button class='btn btn-query' onclick='queryEncoder()'>🔢 查询编码器</button>"
"<button class='btn btn-query' onclick='queryPosSpeed()'>📍 查询位置转速</button>"
"</div>"
"</div>"

"<div class='debug-section'>"
"<div class='section-title'>异常状态查询</div>"
"<div class='exception-group'>"
"<select id='exceptionType'>"
"<option value='0'>电机异常</option>"
"<option value='1'>编码器异常</option>"
"<option value='2'>控制异常</option>"
"<option value='3'>系统异常</option>"
"<option value='4'>全部异常</option>"
"</select>"
"<button class='btn btn-query' onclick='queryException()'>❌ 查询异常</button>"
"</div>"
"</div>"

"<div class='status' id='debugStatus'>"
"调试工具就绪，点击按钮发送CAN指令查询<br>"
"注意：查询结果将通过串口监视器显示，请查看ESP32串口输出"
"</div>"
"</div>"

"<script>"
"function restartMotor(){"
"fetch('/debug/restart').then(r=>r.text()).then(d=>{"
"addStatus('重启电机指令已发送 | '+d);"
"}).catch(e=>addStatus('重启失败: '+e));"
"}"
"function queryTorque(){"
"fetch('/debug/query_torque').then(r=>r.text()).then(d=>{"
"addStatus('查询力矩指令已发送 | '+d);"
"}).catch(e=>addStatus('查询失败: '+e));"
"}"
"function queryPower(){"
"fetch('/debug/query_power').then(r=>r.text()).then(d=>{"
"addStatus('查询功率指令已发送 | '+d);"
"}).catch(e=>addStatus('查询失败: '+e));"
"}"
"function queryEncoder(){"
"fetch('/debug/query_encoder').then(r=>r.text()).then(d=>{"
"addStatus('查询编码器指令已发送 | '+d);"
"}).catch(e=>addStatus('查询失败: '+e));"
"}"
"function queryPosSpeed(){"
"fetch('/debug/query_pos_speed').then(r=>r.text()).then(d=>{"
"addStatus('查询位置转速指令已发送 | '+d);"
"}).catch(e=>addStatus('查询失败: '+e));"
"}"
"function queryException(){"
"let type=document.getElementById('exceptionType').value;"
"fetch('/debug/query_exception?type='+type).then(r=>r.text()).then(d=>{"
"addStatus('查询异常指令已发送(类型:'+type+') | '+d);"
"}).catch(e=>addStatus('查询失败: '+e));"
"}"
"function addStatus(msg){"
"let status=document.getElementById('debugStatus');"
"let time=new Date().toLocaleTimeString();"
"status.innerHTML+='<br>['+time+'] '+msg;"
"status.scrollTop=status.scrollHeight;"
"}"
"</script>"
"</body></html>";

const char* get_web_page_html(void) {
    return web_page_html;
}

const char* get_debug_page_html(void) {
    return debug_page_html;
}