#include "web_interface.h"
#include "motor_control.h"
#include "esp_log.h"
#include <stdio.h>
#include <string.h>

// 网页界面HTML内容
static const char* web_page_html = 
"<!DOCTYPE html>"
"<html><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>电机多模式控制</title>"
"<style>"
"body{font-family:Arial,sans-serif;max-width:700px;margin:30px auto;padding:20px;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%)}"
".container{background:white;padding:30px;border-radius:15px;box-shadow:0 8px 32px rgba(0,0,0,0.3)}"
"h1{color:#333;text-align:center;margin-bottom:30px;font-size:28px}"
".mode-section{margin-bottom:25px;padding:20px;border:2px solid #e0e0e0;border-radius:10px;background:#f9f9f9}"
".mode-title{font-size:18px;font-weight:bold;color:#333;margin-bottom:15px;display:flex;align-items:center}"
".mode-title:before{content:'●';color:#4CAF50;margin-right:8px;font-size:20px}"
".form-group{margin-bottom:15px;display:flex;align-items:center;gap:10px}"
"label{min-width:100px;font-weight:bold;color:#555}"
"input[type='number'],select{padding:8px 12px;border:2px solid #ddd;border-radius:5px;font-size:14px;flex:1}"
"input[type='number']:focus,select:focus{border-color:#4CAF50;outline:none}"
"input[type='radio']{margin-right:8px}"
".radio-group{display:flex;gap:20px;margin-bottom:20px;justify-content:center}"
".radio-option{display:flex;align-items:center;padding:10px 15px;border:2px solid #ddd;border-radius:8px;cursor:pointer;transition:all 0.3s}"
".radio-option:hover{background:#f0f0f0}"
".radio-option.active{border-color:#4CAF50;background:#e8f5e8}"
".btn{background:#4CAF50;color:white;padding:10px 20px;border:none;border-radius:5px;cursor:pointer;font-size:14px;margin:3px;transition:all 0.3s}"
".btn:hover{background:#45a049;transform:translateY(-1px)}"
".btn-danger{background:#f44336}"
".btn-danger:hover{background:#d32f2f}"
".btn-warning{background:#ff9800}"
".btn-warning:hover{background:#f57c00}"
".btn-info{background:#2196F3}"
".btn-info:hover{background:#1976D2}"
".btn-restart{background:#ff9800}"
".btn-restart:hover{background:#f57c00}"
".control-panel{display:flex;justify-content:center;gap:10px;margin:20px 0;flex-wrap:wrap}"
".status{margin-top:20px;padding:15px;border-radius:8px;background:#e3f2fd;border-left:4px solid #2196F3}"
".mode-content{display:none}"
".mode-content.active{display:block}"
".unit{color:#888;font-size:12px;margin-left:5px}"
".error-status{padding:2px 6px;border-radius:4px;font-size:12px;font-weight:bold}"
".error-normal{background:#d4edda;color:#155724}"
".error-warning{background:#fff3cd;color:#856404}"
".error-danger{background:#f8d7da;color:#721c24}"
"</style>"
"</head><body>"
"<div class='container'>"
"<h1>⚙️ 电机多模式控制系统</h1>"

"<div class='radio-group'>"
"<div class='radio-option active' onclick='selectMode(\"velocity\")'>"
"<input type='radio' name='mode' value='velocity' checked id='mode-velocity'>"
"<label for='mode-velocity'>🏃 速度模式</label>"
"</div>"
"<div class='radio-option' onclick='selectMode(\"position\")'>"
"<input type='radio' name='mode' value='position' id='mode-position'>"
"<label for='mode-position'>📍 位置模式</label>"
"</div>"
"<div class='radio-option' onclick='selectMode(\"torque\")'>"
"<input type='radio' name='mode' value='torque' id='mode-torque'>"
"<label for='mode-torque'>💪 力矩模式</label>"
"</div>"
"</div>"

"<div id='velocity-content' class='mode-content active'>"
"<div class='mode-section'>"
"<div class='mode-title'>速度控制</div>"
"<div class='form-group'>"
"<label>目标速度:</label>"
"<input type='number' id='velocity' step='0.1' placeholder='请输入速度值'>"
"<span class='unit'>r/s</span>"
"<button class='btn' onclick='setVelocity()'>设置速度</button>"
"</div>"
"</div>"
"</div>"

"<div id='position-content' class='mode-content'>"
"<div class='mode-section'>"
"<div class='mode-title'>位置控制</div>"
"<div class='form-group'>"
"<label>目标位置:</label>"
"<input type='number' id='position' step='0.1' placeholder='请输入位置值'>"
"<span class='unit'>位置值</span>"
"<button class='btn' onclick='setPosition()'>设置位置</button>"
"</div>"
"<div class='form-group'>"
"<label>角度输入:</label>"
"<input type='number' id='angle' step='0.1' placeholder='请输入角度值'>"
"<span class='unit'>度</span>"
"<button class='btn' onclick='setAngle()'>设置角度</button>"
"</div>"
"</div>"
"</div>"

"<div id='torque-content' class='mode-content'>"
"<div class='mode-section'>"
"<div class='mode-title'>力矩控制</div>"
"<div class='form-group'>"
"<label>目标力矩:</label>"
"<input type='number' id='torque' step='0.01' placeholder='请输入力矩值'>"
"<span class='unit'>Nm</span>"
"<button class='btn' onclick='setTorque()'>设置力矩</button>"
"</div>"
"</div>"
"</div>"

"<div class='control-panel'>"
"<button class='btn btn-info' onclick='enableMotor()'>🔋 使能电机</button>"
"<button class='btn btn-danger' onclick='disableMotor()'>🔌 失能电机</button>"
"<button class='btn btn-warning' onclick='clearErrors()'>🔧 清除错误</button>"
"<button class='btn btn-restart' onclick='restartMotor()'>🔄 重启电机</button>"
"</div>"

"<div class='mode-section'>"
"<div class='mode-title'>⏱️ 状态查询控制</div>"
"<div class='form-group'>"
"<label>查询频率:</label>"
"<input type='number' id='query-frequency' min='1' max='100' step='0.5' value='1.0' placeholder='1.0-100.0'>"
"<span class='unit'>Hz</span>"
"<button class='btn btn-info' onclick='setQueryFrequency()'>设置频率</button>"
"</div>"
"<div class='form-group'>"
"<button class='btn btn-info' id='query-toggle' onclick='toggleAutoQuery()'>🔄 启动自动查询</button>"
"<span id='query-status' style='margin-left:10px;color:#666'>自动查询已停止</span>"
"</div>"
"</div>"

"<div class='status'>"
"<strong>当前状态:</strong> <span id='status'>系统就绪，请选择工作模式</span>"
"</div>"

"<div class='mode-section'>"
"<div class='mode-title'>📊 电机实时状态</div>"
"<div id='motor-status'>"
"<div style='display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-bottom:15px'>"
"<div style='padding:10px;background:#f0f8ff;border-radius:8px'>"
"<strong>🔥 力矩反馈</strong><br>"
"目标力矩: <span id='target-torque'>--</span> Nm<br>"
"当前力矩: <span id='current-torque'>--</span> Nm"
"</div>"
"<div style='padding:10px;background:#f0fff0;border-radius:8px'>"
"<strong>⚡ 功率反馈</strong><br>"
"电功率: <span id='electrical-power'>--</span> W<br>"
"机械功率: <span id='mechanical-power'>--</span> W"
"</div>"
"</div>"
"<div style='display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-bottom:15px'>"
"<div style='padding:10px;background:#fffaf0;border-radius:8px'>"
"<strong>📍 位置转速</strong><br>"
"位置: <span id='position-display'>--</span> 转<br>"
"转速: <span id='velocity-display'>--</span> 转/s"
"</div>"
"<div style='padding:10px;background:#fff0f5;border-radius:8px'>"
"<strong>🔢 编码器</strong><br>"
"多圈计数: <span id='shadow-count'>--</span><br>"
"单圈计数: <span id='count-in-cpr'>--</span>"
"</div>"
"</div>"
"<div style='padding:10px;background:#f5f5f5;border-radius:8px'>"
"<strong>❗ 异常状态</strong><br>"
"电机: <span id='motor-error' class='error-status'>正常</span> | "
"编码器: <span id='encoder-error' class='error-status'>正常</span> | "
"控制器: <span id='controller-error' class='error-status'>正常</span> | "
"系统: <span id='system-error' class='error-status'>正常</span>"
"</div>"
"</div>"
"</div>"
"</div>"

"<script>"
"let currentMode='velocity';"
"function selectMode(mode){"
"currentMode=mode;"
"document.querySelectorAll('.mode-content').forEach(el=>el.classList.remove('active'));"
"document.querySelectorAll('.radio-option').forEach(el=>el.classList.remove('active'));"
"document.getElementById(mode+'-content').classList.add('active');"
"event.currentTarget.classList.add('active');"
"document.getElementById('mode-'+mode).checked=true;"
"fetch('/set_mode?mode='+mode).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='模式切换: '+getModeName(mode)+' | '+d;"
"}).catch(e=>console.log('模式切换失败: '+e));"
"}"
"function getModeName(mode){"
"const names={'velocity':'速度模式','position':'位置模式','torque':'力矩模式'};"
"return names[mode]||mode;"
"}"
"function setVelocity(){"
"let vel=document.getElementById('velocity').value;"
"if(vel===''){alert('请输入速度值');return;}"
"fetch('/set_velocity?value='+vel).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='速度设置: '+vel+' r/s | '+d;"
"}).catch(e=>alert('设置失败: '+e));"
"}"
"function setPosition(){"
"let pos=document.getElementById('position').value;"
"if(pos===''){alert('请输入位置值');return;}"
"fetch('/set_position?value='+pos).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='位置设置: '+pos+' | '+d;"
"}).catch(e=>alert('设置失败: '+e));"
"}"
"function setAngle(){"
"let angle=document.getElementById('angle').value;"
"if(angle===''){alert('请输入角度值');return;}"
"fetch('/set_angle?value='+angle).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='角度设置: '+angle+'° | '+d;"
"}).catch(e=>alert('设置失败: '+e));"
"}"
"function setTorque(){"
"let torque=document.getElementById('torque').value;"
"if(torque===''){alert('请输入力矩值');return;}"
"fetch('/set_torque?value='+torque).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='力矩设置: '+torque+' Nm | '+d;"
"}).catch(e=>alert('设置失败: '+e));"
"}"
"function enableMotor(){"
"fetch('/enable').then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='电机已使能 | '+d;"
"}).catch(e=>alert('操作失败: '+e));"
"}"
"function disableMotor(){"
"fetch('/disable').then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='电机已失能 | '+d;"
"}).catch(e=>alert('操作失败: '+e));"
"}"
"function clearErrors(){"
"fetch('/clear').then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='错误已清除 | '+d;"
"}).catch(e=>alert('操作失败: '+e));"
"}"
"function restartMotor(){"
"fetch('/restart').then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='电机已重启 | '+d;"
"}).catch(e=>alert('操作失败: '+e));"
"}"

"function updateMotorStatus(){"
"fetch('/api/motor_status').then(r=>r.json()).then(data=>{"
"document.getElementById('target-torque').textContent=data.target_torque.toFixed(3)||'--';"
"document.getElementById('current-torque').textContent=data.current_torque.toFixed(3)||'--';"
"document.getElementById('electrical-power').textContent=data.electrical_power.toFixed(2)||'--';"
"document.getElementById('mechanical-power').textContent=data.mechanical_power.toFixed(2)||'--';"
"document.getElementById('position-display').textContent=data.position.toFixed(2)||'--';"
"document.getElementById('velocity-display').textContent=data.velocity.toFixed(3)||'--';"
"document.getElementById('shadow-count').textContent=data.shadow_count||'--';"
"document.getElementById('count-in-cpr').textContent=data.count_in_cpr||'--';"

"updateErrorStatus('motor-error',data.motor_error,data.motor_error_desc);"
"updateErrorStatus('encoder-error',data.encoder_error,data.encoder_error_desc);"
"updateErrorStatus('controller-error',data.controller_error,data.controller_error_desc);"
"updateErrorStatus('system-error',data.system_error,data.system_error_desc);"
"}).catch(e=>console.log('状态更新失败:',e));"
"}"

"function updateErrorStatus(id,code,desc){"
"let elem=document.getElementById(id);"
"elem.className='error-status '+(code?'error-danger':'error-normal');"
"elem.textContent=desc||'正常';"
"}"

"let autoQueryRunning=false;"
"function setQueryFrequency(){"
"let freq=document.getElementById('query-frequency').value;"
"if(freq===''||freq<1||freq>100){alert('请输入有效频率值(1.0-100.0Hz)');return;}"
"fetch('/api/set_query_frequency?freq='+freq).then(r=>r.text()).then(d=>{"
"document.getElementById('status').textContent='查询频率设置: '+freq+' Hz | '+d;"
"}).catch(e=>alert('设置失败: '+e));"
"}"

"function toggleAutoQuery(){"
"let btn=document.getElementById('query-toggle');"
"let status=document.getElementById('query-status');"
"if(autoQueryRunning){"
"fetch('/api/stop_query').then(r=>r.text()).then(d=>{"
"btn.textContent='🔄 启动自动查询';"
"btn.className='btn btn-info';"
"status.textContent='自动查询已停止';"
"status.style.color='#666';"
"autoQueryRunning=false;"
"document.getElementById('status').textContent='自动查询已停止 | '+d;"
"}).catch(e=>alert('停止失败: '+e));"
"}else{"
"fetch('/api/start_query').then(r=>r.text()).then(d=>{"
"btn.textContent='⏸️ 停止自动查询';"
"btn.className='btn btn-warning';"
"status.textContent='自动查询运行中';"
"status.style.color='#4CAF50';"
"autoQueryRunning=true;"
"document.getElementById('status').textContent='自动查询已启动 | '+d;"
"}).catch(e=>alert('启动失败: '+e));"
"}}"

"setInterval(updateMotorStatus,1000);"
"updateMotorStatus();"
"</script>"
"</body></html>";

// 调试页面HTML内容
static const char* debug_page_html = 
"<!DOCTYPE html>"
"<html><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>电机调试工具</title>"
"<style>"
"body{font-family:Arial,sans-serif;max-width:800px;margin:30px auto;padding:20px;background:linear-gradient(135deg,#ff7e5f 0%,#feb47b 100%)}"
".container{background:white;padding:30px;border-radius:15px;box-shadow:0 8px 32px rgba(0,0,0,0.3)}"
"h1{color:#333;text-align:center;margin-bottom:30px;font-size:28px}"
".debug-section{margin-bottom:25px;padding:20px;border:2px solid #e0e0e0;border-radius:10px;background:#f9f9f9}"
".section-title{font-size:18px;font-weight:bold;color:#333;margin-bottom:15px;display:flex;align-items:center}"
".section-title:before{content:'🔧';margin-right:8px;font-size:20px}"
".btn-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:15px;margin:20px 0}"
".btn{background:#4CAF50;color:white;padding:12px 20px;border:none;border-radius:8px;cursor:pointer;font-size:14px;transition:all 0.3s;text-align:center}"
".btn:hover{background:#45a049;transform:translateY(-2px);box-shadow:0 4px 8px rgba(0,0,0,0.2)}"
".btn-restart{background:#ff9800}"
".btn-restart:hover{background:#f57c00}"
".btn-query{background:#2196F3}"
".btn-query:hover{background:#1976D2}"
".exception-group{display:flex;align-items:center;gap:10px;margin-bottom:15px}"
"select{padding:8px 12px;border:2px solid #ddd;border-radius:5px;font-size:14px}"
".status{margin-top:20px;padding:15px;border-radius:8px;background:#e8f5e8;border-left:4px solid #4CAF50;font-family:monospace;max-height:200px;overflow-y:auto}"
".nav-link{display:inline-block;margin:10px 0;color:#2196F3;text-decoration:none;font-weight:bold}"
".nav-link:hover{text-decoration:underline}"
"</style>"
"</head><body>"
"<div class='container'>"
"<h1>🔧 电机调试工具</h1>"
"<a href='/' class='nav-link'>← 返回主控制页面</a>"

"<div class='debug-section'>"
"<div class='section-title'>电机控制指令</div>"
"<div class='btn-grid'>"
"<button class='btn btn-restart' onclick='restartMotor()'>🔄 重启电机</button>"
"</div>"
"</div>"

"<div class='debug-section'>"
"<div class='section-title'>电机状态查询</div>"
"<div class='btn-grid'>"
"<button class='btn btn-query' onclick='queryTorque()'>💪 查询力矩</button>"
"<button class='btn btn-query' onclick='queryPower()'>⚡ 查询功率</button>"
"<button class='btn btn-query' onclick='queryEncoder()'>🔢 查询编码器</button>"
"<button class='btn btn-query' onclick='queryPosSpeed()'>📍 查询位置转速</button>"
"</div>"
"</div>"

"<div class='debug-section'>"
"<div class='section-title'>异常状态查询</div>"
"<div class='exception-group'>"
"<select id='exceptionType'>"
"<option value='0'>电机异常</option>"
"<option value='1'>编码器异常</option>"
"<option value='3'>控制器异常</option>"
"<option value='4'>系统异常</option>"
"</select>"
"<button class='btn btn-query' onclick='queryException()'>❌ 查询异常</button>"
"</div>"
"</div>"

"<div class='status' id='debugStatus'>"
"调试工具就绪，点击按钮发送CAN指令查询<br>"
"注意：查询结果将通过串口监视器显示，请查看ESP32串口输出"
"</div>"
"</div>"

"<script>"
"function restartMotor(){"
"fetch('/debug/restart').then(r=>r.text()).then(d=>{"
"addStatus('重启电机指令已发送 | '+d);"
"}).catch(e=>addStatus('重启失败: '+e));"
"}"
"function queryTorque(){"
"fetch('/debug/query_torque').then(r=>r.text()).then(d=>{"
"addStatus('查询力矩指令已发送 | '+d);"
"}).catch(e=>addStatus('查询失败: '+e));"
"}"
"function queryPower(){"
"fetch('/debug/query_power').then(r=>r.text()).then(d=>{"
"addStatus('查询功率指令已发送 | '+d);"
"}).catch(e=>addStatus('查询失败: '+e));"
"}"
"function queryEncoder(){"
"fetch('/debug/query_encoder').then(r=>r.text()).then(d=>{"
"addStatus('查询编码器指令已发送 | '+d);"
"}).catch(e=>addStatus('查询失败: '+e));"
"}"
"function queryPosSpeed(){"
"fetch('/debug/query_pos_speed').then(r=>r.text()).then(d=>{"
"addStatus('查询位置转速指令已发送 | '+d);"
"}).catch(e=>addStatus('查询失败: '+e));"
"}"
"function queryException(){"
"let type=document.getElementById('exceptionType').value;"
"fetch('/debug/query_exception?type='+type).then(r=>r.text()).then(d=>{"
"addStatus('查询异常指令已发送(类型:'+type+') | '+d);"
"}).catch(e=>addStatus('查询失败: '+e));"
"}"
"function addStatus(msg){"
"let status=document.getElementById('debugStatus');"
"let time=new Date().toLocaleTimeString();"
"status.innerHTML+='<br>['+time+'] '+msg;"
"status.scrollTop=status.scrollHeight;"
"}"
"</script>"
"</body></html>";

const char* get_web_page_html(void) {
    return web_page_html;
}

const char* get_debug_page_html(void) {
    return debug_page_html;
}

// 全局JSON缓冲区
static char motor_status_json_buffer[1024];

const char* get_motor_status_json(void) {
    motor_status_t *status = get_motor_status();
    if (!status) {
        strcpy(motor_status_json_buffer, "{\"error\":\"状态获取失败\"}");
        return motor_status_json_buffer;
    }
    
    // 获取异常描述
    const char *motor_error_desc = get_error_description(status->motor_error, 0);
    const char *encoder_error_desc = get_error_description(status->encoder_error, 1);
    const char *controller_error_desc = get_error_description(status->controller_error, 3);
    const char *system_error_desc = get_error_description(status->system_error, 4);
    
    snprintf(motor_status_json_buffer, sizeof(motor_status_json_buffer),
        "{"
        "\"target_torque\":%.3f,"
        "\"current_torque\":%.3f,"
        "\"electrical_power\":%.2f,"
        "\"mechanical_power\":%.2f,"
        "\"position\":%.2f,"
        "\"velocity\":%.3f,"
        "\"shadow_count\":%ld,"
        "\"count_in_cpr\":%ld,"
        "\"motor_error\":%lu,"
        "\"encoder_error\":%lu,"
        "\"controller_error\":%lu,"
        "\"system_error\":%lu,"
        "\"motor_error_desc\":\"%s\","
        "\"encoder_error_desc\":\"%s\","
        "\"controller_error_desc\":\"%s\","
        "\"system_error_desc\":\"%s\","
        "\"data_valid\":%s,"
        "\"last_update_time\":%lu"
        "}",
        status->target_torque,
        status->current_torque,
        status->electrical_power,
        status->mechanical_power,
        status->position,
        status->velocity,
        (long)status->shadow_count,
        (long)status->count_in_cpr,
        (unsigned long)status->motor_error,
        (unsigned long)status->encoder_error,
        (unsigned long)status->controller_error,
        (unsigned long)status->system_error,
        motor_error_desc,
        encoder_error_desc,
        controller_error_desc,
        system_error_desc,
        status->data_valid ? "true" : "false",
        (unsigned long)status->last_update_time
    );
    
    return motor_status_json_buffer;
}